config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do

  resources :mitupais
  resources :avitos do
    member do
      get :check
    end
  end
  resources :shippings do
    resources :comments, module: :shippings
  end
  resources :telegram_bots do
    collection do
      get :run
      get :stop
    end
  end
  resources :insales do
    collection do
      post :order
      get :check
      get :add_order_webhook
    end
  end
  resources :stocks do
    collection do
      post :bulk_print
      post :download
    end
  end
  resources :stock_transfer_items
  resources :stock_transfers do
    resources :comments, module: :stock_transfers
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_print
    end
  end
  resources :loss_items
  resources :losses do
    resources :comments, module: :losses
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :enter_items
  resources :enters do
    resources :comments, module: :enters
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :inventory_statuses do
    member do
      patch :sort
    end
  end
  resources :stock_transfer_statuses do
    member do
      patch :sort
    end
  end
  resources :loss_statuses do
    member do
      patch :sort
    end
  end
  resources :enter_statuses do
    member do
      patch :sort
    end
  end
  resources :placements do
    resources :locations do
      resources :comments, module: :locations
    end
    collection do
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :return_items
  resources :return_statuses do
    member do
      patch :sort
    end
  end
  resources :returns do
    resources :comments, module: :returns
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :invoice_items
  resources :invoice_statuses do
    member do
      patch :sort
    end
  end
  resources :invoices do
    resources :comments, module: :invoices
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :rent_case_statuses do
    member do
      patch :sort
    end
  end
  resources :dashboards do
    collection do
      post :fullsearch
      post :product_created_at_count_chart
    end
  end
  resources :images do
    collection do
      post :upload
      post :delete
    end
  end
  resources :supply_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_imports do
    collection do
      post :bulk_print
      get :pending_bulk
      get :success_bulk
      get '/:id/start', action: 'start', as: 'start'
      get '/:id/check', action: 'check', as: 'check'
      post :download
    end
  end
  resources :supplies do
    resources :supply_items do
      collection do
        get :slimselect
      end
    end
    collection do
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :incase_item_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_tips do
    member do
      patch :sort
    end
  end
  resources :incase_statuses do
    member do
      patch :sort
    end
  end
  resources :templs
  resources :triggers do
    resources :trigger_actions do
      collection do
        get :values
      end
    end
  end
  resources :delivery_types do
    member do
      patch :sort
    end
  end
  resources :payment_types do
    member do
      patch :sort
    end
  end
  resources :order_items
  resources :order_statuses do
    member do
      patch :sort
    end
  end
  resources :orders do
    resources :deliveries do
      collection do
      end
    end
    resources :comments, module: :orders
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
      get :delivery
    end
    member do
    end
  end
  resources :client_companies do
    collection do
      get :new_turbo
    end
  end
  resources :clients do
    collection do
      post :search
      # post :create_turbo
      # get :new_turbo
      post :bulk_delete
      post :download
    end
  end
  
  resources :email_setups
  resources :incase_items
  resources :incases do
    resources :comments, module: :incases
    member do
      get :act
    end
    collection do
      post :new_supply
      post :create_from_import
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :warehouses do
    resources :places
    member do
      patch :sort
    end
  end
  resources :okrugs do
    member do
      patch :sort
    end
  end
  resources :company_plan_dates do
    resources :comments, module: :company_plan_dates
  end
  resources :companies do
    collection do
      post :search
      post :download
      post :bulk_delete
    end
  end
  resources :detals do
    resources :detal_props do
      collection do
        get :characteristics
      end
    end
  end
  resources :exports do
    member do
      get :download
      post :run
    end
  end
  resources :properties do
    resources :characteristics do
      collection do
        post :search
      end
    end
    collection do
      post :search
    end
  end
  resources :notifications, only: [:index]
  resources :products do
    resources :variants do
      resources :varbinds
      member do
        get :print_etiketka
      end
    end
    member do
      get :print
      patch :sort_image
      post :copy
      get :ai_description
      get :ai_description_get_task_id
      get :ai_description_get_content
      post :ai_description_copy
    end
    collection do
      post :search
      post :print_etiketki
      get :pending_etiketki
      get :success_etiketki
      post :price_edit
      post :price_update
      post :download
      post :bulk_delete
      post :bulk_print
    end
    resources :props do
      collection do
        get :characteristics
      end
    end
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'dashboards#index'
  # root to: 'home#dashboard'
  # get '/dashboard', to: 'home#dashboard', as: 'dashboard'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise patch create users inside service
  get 'users/admin_new' => 'users#admin_new'
  post 'users/admin_create' => 'users#admin_create'
  #########

  resources :users do
    resources :permissions
    member do
      post :read_notification
      post :delete_notification
    end
  end
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
  belongs_to :property
  has_many :props, -> { order(id: :asc) }
  has_many :products, through: :props
  validates :title, presence: true
  before_destroy :check_presence_in_props

  def self.ransackable_attributes(auth_object = nil)
    Characteristic.attribute_names
  end

  private

  def check_presence_in_props
    if props.count > 0
      errors.add(:base, 'Cannot delete characteristic. You have items with it')
      throw(:abort)
    end
  end
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  load_and_authorize_resource
  before_action :get_property
  before_action :set_characteristic, only: %i[show edit update destroy]

  def index
    @characteristics = @property.characteristics
  end

  def show
  end

  def new
    @characteristic = @property.characteristics.build
  end

  def edit
  end

  def create
    puts 'params => ' + params.to_s
    puts 'params property_id => ' + params['property_id'].to_s
    @characteristic = @property.characteristics.build(characteristic_params)
    puts 'characteristic => ' + @characteristic.inspect
    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to property_url(@property), notice: 'Characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to property_url(@property), notice: t('.success') }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @check_destroy = @characteristic.destroy ? true : false
    message = if @check_destroy == true
      flash.now[:success] = t('.success')
    else
      flash.now[:notice] = @characteristic.errors.full_messages.join(' ')
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          render_turbo_flash
        ]
      end
      format.html { redirect_to property_url(@property), notice: t('.success') }
      format.json { head :no_content }
    end
  end

  def search
    if params[:title].present?
      @search_results = @property.characteristics.where('title ILIKE ?', "%#{params[:title]}%").select(:title, :id)
      render json: @search_results, status: :ok
    else
      render json: @search_results, status: :unprocessable_entity
    end
  end

  private

  def get_property
    @property = Property.find(params[:property_id]) if params[:property_id].present?
  end

  def set_characteristic
    @characteristic = @property.characteristics.find(params[:id])
  end

  def characteristic_params
    params.require(:characteristic).permit(:title, :property_id)
  end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_characteristic.html.erb
<%= turbo_frame_tag characteristic, class: 'd-table-row' do %>
  <%= tag.div(class: "d-table-cell", style: 'width: 60px;') do %>
    <%= tag.b characteristic.id%>
  <%end %>
  <%= tag.div(characteristic.title, class: "d-table-cell")%>
  <%= tag.div(class: "d-table-cell d-flex justify-content-end gap-2 align-items-center ps-2") do %>
    <%= link_to edit_icon, edit_property_characteristic_path(@property, characteristic), data: { turbo_frame: '_top'}, class: '' %>
    <%= link_to trash_icon, [@property, characteristic], data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' }, class: "" %>    
  <% end %>
<% end %>

app/views/characteristics/_form.html.erb
<%= form_with(model: [@property, @characteristic]) do |f| %>
    
    <%= render "shared/errors", object: @characteristic %>
      <%# form.label :property_id, style: "display: block" %>
      <%# form.number_field :property_id %>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header fw-bold">
                <%= @property.title if @property.present? %>
            </div>
            <div class="card-body">
              <div class="row">
                  <div class="mb-3 col-md-6">
                    <%= f.label :title, class: "form-label" %>
                    <%= f.text_field :title, class: "form-control" %>
                  </div>
              </div>            
            </div>
            <div class="card-footer">
                <%= f.submit class: "btn btn-primary" %>
                <%= link_to t('back'), property_path(@property), class: "btn btn-outline-primary" %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/characteristics/create.turbo_stream.erb
<%= prepend_flash %>

app/views/characteristics/destroy.turbo_stream.erb
<%= turbo_stream.remove @characteristic if @check_destroy == true %>
<%= prepend_flash %>

app/views/characteristics/edit.html.erb
<%= render 'characteristics/form', characteristic: @characteristic%>

app/views/characteristics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Characteristics</h1>

<div id="characteristics">
    <%= render @characteristics %>
</div>

<%# link_to "New characteristic", new_characteristic_path %>

app/views/characteristics/new.html.erb
<%= render 'characteristics/form', characteristic: @characteristic%>

app/views/characteristics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @characteristic %>

<div>
  <%= link_to "Edit this characteristic", edit_characteristic_path(@characteristic) %> |
  <%= link_to "Back to characteristics", characteristics_path %>

  <%= button_to "Destroy this characteristic", @characteristic, method: :delete %>
</div>