config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do

  resources :mitupais
  resources :avitos do
    member do
      get :check
    end
  end
  resources :shippings do
    resources :comments, module: :shippings
  end
  resources :telegram_bots do
    collection do
      get :run
      get :stop
    end
  end
  resources :insales do
    collection do
      post :order
      get :check
      get :add_order_webhook
    end
  end
  resources :stocks do
    collection do
      post :bulk_print
      post :download
    end
  end
  resources :stock_transfer_items
  resources :stock_transfers do
    resources :comments, module: :stock_transfers
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_print
    end
  end
  resources :loss_items
  resources :losses do
    resources :comments, module: :losses
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :enter_items
  resources :enters do
    resources :comments, module: :enters
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :inventory_statuses do
    member do
      patch :sort
    end
  end
  resources :stock_transfer_statuses do
    member do
      patch :sort
    end
  end
  resources :loss_statuses do
    member do
      patch :sort
    end
  end
  resources :enter_statuses do
    member do
      patch :sort
    end
  end
  resources :placements do
    resources :locations do
      resources :comments, module: :locations
    end
    collection do
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :return_items
  resources :return_statuses do
    member do
      patch :sort
    end
  end
  resources :returns do
    resources :comments, module: :returns
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :invoice_items
  resources :invoice_statuses do
    member do
      patch :sort
    end
  end
  resources :invoices do
    resources :comments, module: :invoices
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :rent_case_statuses do
    member do
      patch :sort
    end
  end
  resources :dashboards do
    collection do
      post :fullsearch
      post :product_created_at_count_chart
    end
  end
  resources :images do
    collection do
      post :upload
      post :delete
    end
  end
  resources :supply_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_imports do
    collection do
      post :bulk_print
      get :pending_bulk
      get :success_bulk
      get '/:id/start', action: 'start', as: 'start'
      get '/:id/check', action: 'check', as: 'check'
      post :download
    end
  end
  resources :supplies do
    resources :supply_items do
      collection do
        get :slimselect
      end
    end
    collection do
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :incase_item_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_tips do
    member do
      patch :sort
    end
  end
  resources :incase_statuses do
    member do
      patch :sort
    end
  end
  resources :templs
  resources :triggers do
    resources :trigger_actions do
      collection do
        get :values
      end
    end
  end
  resources :delivery_types do
    member do
      patch :sort
    end
  end
  resources :payment_types do
    member do
      patch :sort
    end
  end
  resources :order_items
  resources :order_statuses do
    member do
      patch :sort
    end
  end
  resources :orders do
    resources :deliveries do
      collection do
      end
    end
    resources :comments, module: :orders
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
      get :delivery
    end
    member do
    end
  end
  resources :client_companies do
    collection do
      get :new_turbo
    end
  end
  resources :clients do
    collection do
      post :search
      # post :create_turbo
      # get :new_turbo
      post :bulk_delete
      post :download
    end
  end
  
  resources :email_setups
  resources :incase_items
  resources :incases do
    resources :comments, module: :incases
    member do
      get :act
    end
    collection do
      post :new_supply
      post :create_from_import
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :warehouses do
    resources :places
    member do
      patch :sort
    end
  end
  resources :okrugs do
    member do
      patch :sort
    end
  end
  resources :company_plan_dates do
    resources :comments, module: :company_plan_dates
  end
  resources :companies do
    collection do
      post :search
      post :download
      post :bulk_delete
    end
  end
  resources :detals do
    resources :detal_props do
      collection do
        get :characteristics
      end
    end
  end
  resources :exports do
    member do
      get :download
      post :run
    end
  end
  resources :properties do
    resources :characteristics do
      collection do
        post :search
      end
    end
    collection do
      post :search
    end
  end
  resources :notifications, only: [:index]
  resources :products do
    resources :variants do
      resources :varbinds
      member do
        get :print_etiketka
      end
    end
    member do
      get :print
      patch :sort_image
      post :copy
      get :ai_description
      get :ai_description_get_task_id
      get :ai_description_get_content
      post :ai_description_copy
    end
    collection do
      post :search
      post :print_etiketki
      get :pending_etiketki
      get :success_etiketki
      post :price_edit
      post :price_update
      post :download
      post :bulk_delete
      post :bulk_print
    end
    resources :props do
      collection do
        get :characteristics
      end
    end
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'dashboards#index'
  # root to: 'home#dashboard'
  # get '/dashboard', to: 'home#dashboard', as: 'dashboard'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise patch create users inside service
  get 'users/admin_new' => 'users#admin_new'
  post 'users/admin_create' => 'users#admin_create'
  #########

  resources :users do
    resources :permissions
    member do
      post :read_notification
      post :delete_notification
    end
  end
end

app/models/supply.rb
# frozen_string_literal: true

# Supply < ApplicationRecord
class Supply < ApplicationRecord
  include NormalizeDataWhiteSpace
  audited
  belongs_to :supply_status
  belongs_to :company
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'
  belongs_to :buyer, class_name: 'Company', foreign_key: 'buyer_id'
  has_many :supply_items, dependent: :destroy
  accepts_nested_attributes_for :supply_items, allow_destroy: true
  has_associated_audits
  after_initialize :add_title

  validates :supply_items, presence: true
  validates :title, presence: true

  after_create_commit { broadcast_prepend_to 'supplies_page1' }
  after_update_commit { broadcast_replace_to 'supplies' }
  after_destroy_commit { broadcast_remove_to 'supplies' }

  def self.ransackable_attributes(auth_object = nil)
    Supply.attribute_names
  end

  def self.ransackable_associations(auth_object = nil)
    %w[associated_audits audits company supply_items]
  end


  private

  def add_title
    self.title = 'Поступление'
  end

end

app/controllers/supplies_controller.rb
# frozen_string_literal: true

# SuppliesController handles the CRUD operations for supplies.
class SuppliesController < ApplicationController
  load_and_authorize_resource
  before_action :set_supply, only: %i[show edit update destroy]
  include ActionView::RecordIdentifier
  include SearchQueryRansack
  include DownloadExcel
  include NestedItem

  def index
    @search = Supply.includes(:company, :supply_items).ransack(search_params)
    @search.sorts = 'id desc' if @search.sorts.empty?
    @supplies = @search.result(distinct: true).paginate(page: params[:page], per_page: 100)
    respond_to(&:html)
  end

  def show; end

  def new
    if params[:incase_ids].present?
      @supply = Supply.new(manager_id: current_user.id)
      company_id_array = []
      params[:incase_ids].each do |incase_id|
        incase = Incase.find(incase_id)
        company_id_array << incase.company_id
        p_status_id = params[:incase_item_status_id]
        items = p_status_id.present? ? incase.incase_items.where(incase_item_status_id: p_status_id) : incase.incase_items
        items.each do |inc|
          @supply.supply_items.build(variant_id: inc.variant.id, quantity: inc.quantity, price: inc.price)
        end
      end
      @supply.company_id = company_id_array.uniq[0]
      @supply
    else
      @supply = Supply.new
      @supply.supply_items.build
    end
  end

  def edit; end

  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to supplies_url, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to supplies_url, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @supply.destroy

    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_supply
    @supply = Supply.find(params[:id])
  end

  def supply_params
    params.require(:supply).permit(
      :buyer_id,
      :company_id,
      :title,
      :in_number,
      :in_date,
      :supply_status_id,
      :manager_id,
      :warehouse_id,
      supply_items_attributes: %i[id variant_id quantity price vat sum _destroy]
    )
  end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_with(model: supply, data: { controller: 'choose slimselect' }, class: 'supply-form' ) do |f| %>
    <%= render 'shared/errors', object: supply %>

    <div class="card">
        <div class="card-header d-flex align-items-center gap-3 px-2">
            <div class="d-flex justify-content-between align-items-center gap-3">
                <%= f.select :supply_status_id, SupplyStatus.order(:position).pluck(:title, :id), {include_blank: false, prompt: t('status')}, {class: "form-select border-primary-subtle"} %>
                <%= tabs_head('supply', [ ['main', t(:main)] ]) if !f.object.new_record? %>
            </div>
            <div class="d-flex ms-auto justify-content-between align-items-center gap-3">
                <%= f.select :manager_id, User.pluck(:name, :id), {include_blank: false, selected: current_user}, {class: "form-select border-primary-subtle"} %>
                <%= link_to history_icon, audited_auditable_audits_path(auditable_type: "supply", auditable_id: supply.id), class: 'btn btn-outline-success d-flex', data: {turbo_frame: "offcanvas_history"} if !f.object.new_record? %>
            </div>
        </div>
        <div class="card-body pt-0">
            <div class="tab-content">
                <div class="tab-pane active" id="main_tab" role="tabpanel" aria-labelledby="main_tab">
                    <div class="row">
                        <%= render 'form_data', f: f %>
                    </div>
                    <div class="row" data-controller="calculate">
                        <%= render 'nested', f: f, supply: supply %>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <%= f.submit t('save'), class: "btn btn-primary" %>
            <%= link_to t('back'), supplies_path, class: "btn btn-outline-primary" %>
        </div>
    </div>
<% end %>

app/views/supplies/_form_data.html.erb
<div class="mb-3 col-4 ps-0 pe-1 ">
    <%= f.label :buyer_id, class: "form-label" %>
    <%= f.select :buyer_id, Company.our.pluck(:short_title, :id), {include_blank: false}, { class: "form-select"} %>
</div>
<div class="mb-3 col-7 ps-0 pe-1 "></div>
<div class="mb-3 col-3 ps-0 pe-1 ">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>
</div>
<div class="mb-3 col-3 ps-0 pe-1 ">
    <%= f.label :company_id, class: "form-label" %>
    <%= f.select :company_id, Company.collection_for_select(f.object.company_id), {include_blank: true}, 
                            {  class: "form-select", data: {controller: 'slimselect', search_url:  "/companies/search"} } %>
</div>
<div class="mb-3 col-2 ps-0 pe-1 ">
    <%= f.label :in_number, class: "form-label" %>
    <%= f.text_field :in_number, class: "form-control" %>
</div>
<div class="mb-3 col-2 ps-0 pe-1 ">
    <%= f.label :in_date, class: "form-label" %>
    <%= f.date_field :in_date, class: "form-control bg-light cursor-pointer", data: { controller: 'flatpickr',flatpickr_alt_input: "true", flatpickr_alt_format: "d-m-Y" } %>
</div>
<div class="mb-3 col-2 ps-0 pe-1 ">
    <%= f.label :warehouse_id, class: "form-label" %>
    <%= f.select :warehouse_id, Warehouse.pluck(:title, :id), {include_blank: false}, {class: "form-select"}%>
</div>

app/views/supplies/_nested.html.erb
<%= tag.div class: "col-2 my-3" do %>
    <%= link_to add_icon, new_nested_supplies_path, class: "btn btn-primary", data: { turbo_stream: true } %>
<% end %>

<%= tag.div class: "col-12 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3" do %>
    <%= tag.div class: "row py-2 px-0" do %>
        <%= tag.div(t('helpers.label.supply_item.variant_id'), class: 'col-6 fw-semibold') %>
        <%= tag.div(t('helpers.label.supply_item.quantity'), class: 'col-1 fw-semibold') %>
        <%= tag.div(t('helpers.label.supply_item.price'), class: 'col-1 fw-semibold') %>
        <%= tag.div(t('helpers.label.supply_item.nds'), class: 'col-1 fw-semibold') %>
        <%= tag.div(t('helpers.label.supply_item.sum'), class: 'col-1 fw-semibold') %>
        <%= tag.div('', class: 'col fw-semibold') %>
    <% end %>
    
    <%= turbo_frame_tag supply, :supply_items, class: "container" do %>
        <%= f.fields_for :supply_items do |ff| %>
            <%= render partial: "shared/items_form_data", 
                                 locals: { f: ff,
                                                     variant: nil,
                                                     nested_url: "/supplies/slimselect_nested_item",
                                                     object_turbo_frame_tag: "supply_item_#{ ff.object.persisted? ? ff.object.id : Time.now.to_i}",
                                                     remove_element_path: "/supplies/remove_nested?supply_item_id=#{ ff.object.persisted? ? ff.object.id : Time.now.to_i }",
                                                     discount_field: false } %>
        <% end %>
    <% end %>
    
    <%= render partial: 'shared/nested_footer', locals: { discount_field: false } %>
    <%= render partial: 'shared/recalculate' %>
<% end %>

app/views/supplies/_supply.html.erb
<%= turbo_frame_tag supply, class: "d-flex list-group-item py-2 border-start-0 border-end-0 row justify-content-between align-items-center px-0" do %>
    <%= tag.div class: "col-1" do %>
        <%=tag.div class: 'form-check' do %>
            <%= check_box_tag "supply_ids[]", supply.id, false, {class: 'checkboxes form-check-input', data: { 'selectall_target': 'checkbox', action: "change->selectall#toggleParent"}, form: :bulk_action_form } %>
            <%=tag.label class: 'form-check-label' do %><%= tag.b( supply.id ) %><% end %>
        <% end %>
        <%= supply.created_at.strftime("%d/%m/%Y %H:%M") %>
    <% end %>
    <%= tag.div class: "col-1" do %>
        <%= tag.span(   supply.supply_status.title,
                        class: 'text-wrap w-100', 
                        style: 'background-color:'+supply.supply_status.color,
                        data: {controller: 'badge', badge_target: 'value', bg_color: supply.supply_status.color }) if supply.supply_status %>
    <% end %>
    <%= tag.div( supply.buyer&.short_title , class: "col-2") %>
    <%= tag.div( supply.company.present? ? supply.company&.short_title : ''  , class: "col-2") %>
    <%= tag.div class: "col-2" do %>
        <%= tag.div( supply.title ? supply.title : '' , class: "") %>
        <%=tag.span(t('helpers.label.supply.in_number'))%> <%= tag.span(supply.in_number) %></br>
        <%=tag.span(t('helpers.label.supply.in_date'))%> <%= tag.span(supply.in_date ? supply.in_date.strftime("%d/%m/%Y") : '') %>
    <% end %>
    <%# tag.div( supply.sum  , class: "col-1") %>

    <%= tag.div(class: "col-2 d-flex justify-content-end gap-2 align-items-center") do %>
        <%= render 'shared/edit_delete_link', object: supply %>
   <% end %>
<% end %>

app/views/supplies/edit.html.erb
<%= render 'shared/new_edit', object: @supply, tip: :edit %>

app/views/supplies/index.html.erb
<div class="row index-head mb-3">
  <div class="col-md-6 index-head__title">
    <h1 class="h3 d-inline align-middle"><%= Supply.model_name.human(count: 2)%></h1>
  </div>
  <div class="col-md-6 d-flex justify-content-end index-head__buttons">
  <%= form_with url: bulk_print_supplies_path, method: :post, id: :bulk_action_form  do |f| %>
    <% if Templ.supply_print.presence %>
    <%= button_print %>
    <ul class="dropdown-menu">
      <% Templ.supply_print.each do |templ|%>
        <%= f.button type: :submit, value: "templ_id##{templ.id}", class: "dropdown-item" do %>
          <%= templ.title %>
        <% end %>
      <% end %>
    <% end %>
    </ul>
    <%= render 'shared/download_excel_buttons', f: f, object: Supply.new %>
  <% end %>
    <%= render 'shared/index_filter' if lookup_context.find_all("supplies/_filter").any? %>
    <%= link_to arrow_clockwise_icon, supplies_path(search_cancel: true), class: 'btn btn-outline-primary me-2', data: {turbo: false}  %>
    <%= link_to add_icon, new_supply_path, class: "btn btn-primary" %>
  </div>
</div>

<%= render 'filter', q: @search, title: t('filter') if lookup_context.find_all("supplies/_filter").any?%>

<%=tag.div class: "card" do %>
  <%=tag.div class: "card-header pb-0" do %>
    <%=tag.h5 class: "card-title mb-0" do %>
      <%= page_entries_info(@supplies).to_s.gsub('Supply','').gsub('поступления','').html_safe %>
    <% end %>
  <% end %>
  <%=tag.div class: "card-body" do %>
    <%=tag.div(id: "datatables-supplies", class: "col-sm-12 list-group list-group-striped", data: {controller:"selectall"}) do %>  
      <%= tag.div class:"row py-2 px-0 justify-content-between align-items-center" do %>
        <%= div_check_box_tag_all %>
        <%= tag.div( t( 'helpers.label.supply.supply_status_id' ), class: 'col-1 fw-semibold' )%>
        <%= tag.div( t( 'helpers.label.supply.buyer_id' ), class: 'col-2 fw-semibold' )%> 
        <%= tag.div( t( 'helpers.label.supply.company_id' ), class: 'col-2 fw-semibold' )%> 
        <%= tag.div( '', class: 'col-2 fw-semibold' )%>
        <%# tag.div( t( 'helpers.label.supply.sum' ), class: 'col-1 fw-semibold' )%>
        <%= tag.div('', class: 'col-2 fw-semibold')%>
      <% end %>
      
      <% if !@supplies.previous_page.present? && !params[:q]&.values&.reject(&:blank?).present? %>
        <%= turbo_stream_from "supplies_page1" %>
      <% else %>
        <%= turbo_stream_from "supplies" %>
      <% end %>

      <%= turbo_frame_tag 'supplies' do %>
          <%= render @supplies %>
      <% end %>
    <% end %>

    <%= render "shared/paginate", f: @supplies %>
  <% end %>
<% end %>

app/views/supplies/new.html.erb
<%= render 'shared/new_edit', object: @supply, tip: :new %>

app/views/supplies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supply %>

<div>
  <%= link_to "Edit this supply", edit_supply_path(@supply) %> |
  <%= link_to "Back to supplies", supplies_path %>

  <%= button_to "Destroy this supply", @supply, method: :delete %>
</div>