config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do

  resources :mitupais
  resources :avitos do
    member do
      get :check
    end
  end
  resources :shippings do
    resources :comments, module: :shippings
  end
  resources :telegram_bots do
    collection do
      get :run
      get :stop
    end
  end
  resources :insales do
    collection do
      post :order
      get :check
      get :add_order_webhook
    end
  end
  resources :stocks do
    collection do
      post :bulk_print
      post :download
    end
  end
  resources :stock_transfer_items
  resources :stock_transfers do
    resources :comments, module: :stock_transfers
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_print
    end
  end
  resources :loss_items
  resources :losses do
    resources :comments, module: :losses
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :enter_items
  resources :enters do
    resources :comments, module: :enters
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :inventory_statuses do
    member do
      patch :sort
    end
  end
  resources :stock_transfer_statuses do
    member do
      patch :sort
    end
  end
  resources :loss_statuses do
    member do
      patch :sort
    end
  end
  resources :enter_statuses do
    member do
      patch :sort
    end
  end
  resources :placements do
    resources :locations do
      resources :comments, module: :locations
    end
    collection do
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :return_items
  resources :return_statuses do
    member do
      patch :sort
    end
  end
  resources :returns do
    resources :comments, module: :returns
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :invoice_items
  resources :invoice_statuses do
    member do
      patch :sort
    end
  end
  resources :invoices do
    resources :comments, module: :invoices
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :rent_case_statuses do
    member do
      patch :sort
    end
  end
  resources :dashboards do
    collection do
      post :fullsearch
      post :product_created_at_count_chart
    end
  end
  resources :images do
    collection do
      post :upload
      post :delete
    end
  end
  resources :supply_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_imports do
    collection do
      post :bulk_print
      get :pending_bulk
      get :success_bulk
      get '/:id/start', action: 'start', as: 'start'
      get '/:id/check', action: 'check', as: 'check'
      post :download
    end
  end
  resources :supplies do
    resources :supply_items do
      collection do
        get :slimselect
      end
    end
    collection do
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :incase_item_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_tips do
    member do
      patch :sort
    end
  end
  resources :incase_statuses do
    member do
      patch :sort
    end
  end
  resources :templs
  resources :triggers do
    resources :trigger_actions do
      collection do
        get :values
      end
    end
  end
  resources :delivery_types do
    member do
      patch :sort
    end
  end
  resources :payment_types do
    member do
      patch :sort
    end
  end
  resources :order_items
  resources :order_statuses do
    member do
      patch :sort
    end
  end
  resources :orders do
    resources :deliveries do
      collection do
      end
    end
    resources :comments, module: :orders
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
      get :delivery
    end
    member do
    end
  end
  resources :client_companies do
    collection do
      get :new_turbo
    end
  end
  resources :clients do
    collection do
      post :search
      # post :create_turbo
      # get :new_turbo
      post :bulk_delete
      post :download
    end
  end
  
  resources :email_setups
  resources :incase_items
  resources :incases do
    resources :comments, module: :incases
    member do
      get :act
    end
    collection do
      post :new_supply
      post :create_from_import
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :warehouses do
    resources :places
    member do
      patch :sort
    end
  end
  resources :okrugs do
    member do
      patch :sort
    end
  end
  resources :company_plan_dates do
    resources :comments, module: :company_plan_dates
  end
  resources :companies do
    collection do
      post :search
      post :download
      post :bulk_delete
    end
  end
  resources :detals do
    resources :detal_props do
      collection do
        get :characteristics
      end
    end
  end
  resources :exports do
    member do
      get :download
      post :run
    end
  end
  resources :properties do
    resources :characteristics do
      collection do
        post :search
      end
    end
    collection do
      post :search
    end
  end
  resources :notifications, only: [:index]
  resources :products do
    resources :variants do
      resources :varbinds
      member do
        get :print_etiketka
      end
    end
    member do
      get :print
      patch :sort_image
      post :copy
      get :ai_description
      get :ai_description_get_task_id
      get :ai_description_get_content
      post :ai_description_copy
    end
    collection do
      post :search
      post :print_etiketki
      get :pending_etiketki
      get :success_etiketki
      post :price_edit
      post :price_update
      post :download
      post :bulk_delete
      post :bulk_print
    end
    resources :props do
      collection do
        get :characteristics
      end
    end
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'dashboards#index'
  # root to: 'home#dashboard'
  # get '/dashboard', to: 'home#dashboard', as: 'dashboard'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise patch create users inside service
  get 'users/admin_new' => 'users#admin_new'
  post 'users/admin_create' => 'users#admin_create'
  #########

  resources :users do
    resources :permissions
    member do
      post :read_notification
      post :delete_notification
    end
  end
end

app/models/detal_prop.rb
class DetalProp < ApplicationRecord
  belongs_to :property
  belongs_to :characteristic
  belongs_to :detal

  default_scope -> { order(id: :asc) }

  validates :characteristic_id, uniqueness: {scope: [:property, :detal]}
  
  include ActionView::RecordIdentifier

  after_create_commit do 
    broadcast_append_to [detal, :detal_props], target: dom_id(detal, :detal_props), partial: "detal_props/detal_prop", locals: { prop: self, detal: detal  }
    broadcast_update_to [detal, :detal_props], target: dom_id(detal, dom_id(DetalProp.new)), html: ''
  end

  after_update_commit do
      broadcast_replace_to [detal, :detal_props], target: dom_id(detal, dom_id(self)), partial: "detal_props/detal_prop", locals: { prop: self, detal: detal }
  end

  after_destroy_commit do
    broadcast_remove_to [detal, :detal_props], target: dom_id(detal, dom_id(self))
  end

end

app/controllers/detal_props_controller.rb
class DetalPropsController < ApplicationController
  load_and_authorize_resource
  before_action :set_detal
  before_action :set_detal_prop, only: %i[ show edit update destroy ]

  # GET /detal_props or /detal_props.json
  def index
    @detal_props = @detal.detal_props  
  end

  # GET /detal_props/1 or /detal_props/1.json
  def show
  end

  # GET /detal_props/new
  def new
    @detal_prop = @detal.detal_props.build
    @characteristics = []
  end

  # GET /detal_props/1/edit
  def edit
    @selected = @detal_prop.property.id
    @characteristics = @detal_prop.property.characteristics.pluck(:title, :id)
  end

  # POST /detal_props or /detal_props.json
  def create
    @detal_prop = @detal.detal_props.build(detal_prop_params)

    respond_to do |format|
      if @detal_prop.save
        flash.now[:success] = t(".success")
        format.turbo_stream do
          render turbo_stream: [
            render_turbo_flash
          ]
        end
        format.html { redirect_to detal_detal_props_url(@detal), notice: "Detal prop was successfully created." }
        format.json { render :show, status: :created, location: @detal_prop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detal_prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detal_props/1 or /detal_props/1.json
  def update
    respond_to do |format|
      if @detal_prop.update(detal_prop_params)
        flash.now[:success] = t(".success")
        format.turbo_stream do
          render turbo_stream: [
            render_turbo_flash
          ]
        end
        format.html { redirect_to detal_detal_prop_url(@detal), notice: "Detal prop was successfully updated." }
        format.json { render :show, status: :ok, location: @detal_prop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detal_prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detal_props/1 or /detal_props/1.json
  def destroy
    @detal_prop.destroy!

    respond_to do |format|
      format.html { redirect_to detal_props_url, notice: "Detal prop was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { flash.now[:success] = t(".success") }
    end
  end

  def characteristics

    @target = params[:turboId]
    @selected = params[:selected_id]
    @property = Property.includes(:characteristics).find(params[:selected_id])
    detal_prop_id = params[:turboId].split('_')[2] if !params[:turboId].include?('new')
    detal_prop = params[:turboId].include?('new') ? @detal.detal_props.build : @detal.detal_prop.find(detal_prop_id)
    
    @characteristics = @property.characteristics.pluck(:title, :id)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: 
          turbo_stream.replace(
            @target, partial: "detal_props/form", locals: {detal_prop: detal_prop}
          )
      end
    end

  end

  private

    def set_detal
      @detal = Detal.find(params[:detal_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_detal_prop
      @detal_prop = @detal.detal_props.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detal_prop_params
      params.require(:detal_prop).permit(:detal_id, :property_id, :characteristic_id)
    end
end

app/helpers/detal_props_helper.rb
module DetalPropsHelper
end

app/views/detal_props/_detal_prop.html.erb
<%= turbo_frame_tag "detal_prop_#{detal_prop.id}_detal_#{detal.id}", class: "row" do %>
  <div class="mb-3 col-4">
      <%= detal_prop.property.title.to_s%>
  </div>
  <div class="mb-3 col-4">
      <%= detal_prop.property.c_val(detal_prop.characteristic_id).title.to_s if detal_prop.present? %>
  </div>
  <div class="mb-3 col-4 d-flex justify-content-end gap-2 align-items-center">
      <%= link_to edit_icon, [:edit, detal, detal_prop], class: '' %>
      <%= link_to trash_icon, [detal,detal_prop], data: { "turbo-method": :delete, 'turbo-confirm': 'Are you sure?' }, class:"" %>
  </div>
<% end %>

app/views/detal_props/_form.html.erb
<%= turbo_frame_tag dom_id(@detal, dom_id(detal_prop))  do %>
    <%= form_with(model: [@detal, detal_prop], class: "row align-items-center d-flex justify-content-center mb-3", data: {}) do |f|%>
        <%= render 'shared/errors', object: detal_prop %>
        
        <div class="col-4">

        <%= f.label :property_id, t('property_one'), class: "visually-hidden" %>
        <%= f.select :property_id,  options_for_select(Property.pluck(:title, :id), @selected), 
                                    {include_blank: false, prompt: t('property_one')}, 
                                    {data: {controller: 'slimselect',
                                            nested_url:  characteristics_detal_detal_props_path}}  %>
        </div>
        <div class="col-4">
        <%= f.label :characteristic_id, t('characteristic_one'), class: "visually-hidden" %>
        <%= f.select :characteristic_id, @characteristics.present? ? @characteristics : [], 
                        {include_blank: false, prompt: t('characteristic_one')}, 
                                        {data: {controller: 'slimselect',
                                        search_url:  "/properties/#{@selected}/characteristics/search",}}  %>
        </div>

        <div class="col-4 d-flex justify-content-end gap-2 align-items-center">
            <%= f.submit t(:save), class: "btn btn-primary" %>
            <%= link_to close_icon, :back, class: "btn btn-outline-primary" %>
        </div>

    <% end %>
<% end %>

app/views/detal_props/edit.html.erb
<%= render 'detal_props/form', detal_prop: @detal_prop %>

app/views/detal_props/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Detal props</h1>

<div id="detal_props">
  <% @detal_props.each do |detal_prop| %>
    <%= render detal_prop %>
    <p>
      <%= link_to "Show this detal prop", detal_prop %>
    </p>
  <% end %>
</div>

<%= link_to "New detal prop", new_detal_prop_path %>

app/views/detal_props/new.html.erb
<%= render 'detal_props/form', detal_prop: @detal_prop%>

app/views/detal_props/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detal_prop %>

<div>
  <%= link_to "Edit this detal prop", edit_detal_prop_path(@detal_prop) %> |
  <%= link_to "Back to detal props", detal_props_path %>

  <%= button_to "Destroy this detal prop", @detal_prop, method: :delete %>
</div>