config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do

  resources :mitupais
  resources :avitos do
    member do
      get :check
    end
  end
  resources :shippings do
    resources :comments, module: :shippings
  end
  resources :telegram_bots do
    collection do
      get :run
      get :stop
    end
  end
  resources :insales do
    collection do
      post :order
      get :check
      get :add_order_webhook
    end
  end
  resources :stocks do
    collection do
      post :bulk_print
      post :download
    end
  end
  resources :stock_transfer_items
  resources :stock_transfers do
    resources :comments, module: :stock_transfers
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_print
    end
  end
  resources :loss_items
  resources :losses do
    resources :comments, module: :losses
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :enter_items
  resources :enters do
    resources :comments, module: :enters
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :inventory_statuses do
    member do
      patch :sort
    end
  end
  resources :stock_transfer_statuses do
    member do
      patch :sort
    end
  end
  resources :loss_statuses do
    member do
      patch :sort
    end
  end
  resources :enter_statuses do
    member do
      patch :sort
    end
  end
  resources :placements do
    resources :locations do
      resources :comments, module: :locations
    end
    collection do
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :return_items
  resources :return_statuses do
    member do
      patch :sort
    end
  end
  resources :returns do
    resources :comments, module: :returns
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
    end
  end
  resources :invoice_items
  resources :invoice_statuses do
    member do
      patch :sort
    end
  end
  resources :invoices do
    resources :comments, module: :invoices
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :rent_case_statuses do
    member do
      patch :sort
    end
  end
  resources :dashboards do
    collection do
      post :fullsearch
      post :product_created_at_count_chart
    end
  end
  resources :images do
    collection do
      post :upload
      post :delete
    end
  end
  resources :supply_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_imports do
    collection do
      post :bulk_print
      get :pending_bulk
      get :success_bulk
      get '/:id/start', action: 'start', as: 'start'
      get '/:id/check', action: 'check', as: 'check'
      post :download
    end
  end
  resources :supplies do
    resources :supply_items do
      collection do
        get :slimselect
      end
    end
    collection do
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
    end
  end
  resources :incase_item_statuses do
    member do
      patch :sort
    end
  end
  resources :incase_tips do
    member do
      patch :sort
    end
  end
  resources :incase_statuses do
    member do
      patch :sort
    end
  end
  resources :templs
  resources :triggers do
    resources :trigger_actions do
      collection do
        get :values
      end
    end
  end
  resources :delivery_types do
    member do
      patch :sort
    end
  end
  resources :payment_types do
    member do
      patch :sort
    end
  end
  resources :order_items
  resources :order_statuses do
    member do
      patch :sort
    end
  end
  resources :orders do
    resources :deliveries do
      collection do
      end
    end
    resources :comments, module: :orders
    collection do
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :bulk_print
      post :download
      post :bulk_status
      post :bulk_status_update
      get :delivery
    end
    member do
    end
  end
  resources :client_companies do
    collection do
      get :new_turbo
    end
  end
  resources :clients do
    collection do
      post :search
      # post :create_turbo
      # get :new_turbo
      post :bulk_delete
      post :download
    end
  end
  
  resources :email_setups
  resources :incase_items
  resources :incases do
    resources :comments, module: :incases
    member do
      get :act
    end
    collection do
      post :new_supply
      post :create_from_import
      post :bulk_print
      get :slimselect_nested_item
      get :new_nested
      post :remove_nested
      post :download
      post :bulk_status
      post :bulk_status_update
    end
  end
  resources :warehouses do
    resources :places
    member do
      patch :sort
    end
  end
  resources :okrugs do
    member do
      patch :sort
    end
  end
  resources :company_plan_dates do
    resources :comments, module: :company_plan_dates
  end
  resources :companies do
    collection do
      post :search
      post :download
      post :bulk_delete
    end
  end
  resources :detals do
    resources :detal_props do
      collection do
        get :characteristics
      end
    end
  end
  resources :exports do
    member do
      get :download
      post :run
    end
  end
  resources :properties do
    resources :characteristics do
      collection do
        post :search
      end
    end
    collection do
      post :search
    end
  end
  resources :notifications, only: [:index]
  resources :products do
    resources :variants do
      resources :varbinds
      member do
        get :print_etiketka
      end
    end
    member do
      get :print
      patch :sort_image
      post :copy
      get :ai_description
      get :ai_description_get_task_id
      get :ai_description_get_content
      post :ai_description_copy
    end
    collection do
      post :search
      post :print_etiketki
      get :pending_etiketki
      get :success_etiketki
      post :price_edit
      post :price_update
      post :download
      post :bulk_delete
      post :bulk_print
    end
    resources :props do
      collection do
        get :characteristics
      end
    end
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'dashboards#index'
  # root to: 'home#dashboard'
  # get '/dashboard', to: 'home#dashboard', as: 'dashboard'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # devise patch create users inside service
  get 'users/admin_new' => 'users#admin_new'
  post 'users/admin_create' => 'users#admin_create'
  #########

  resources :users do
    resources :permissions
    member do
      post :read_notification
      post :delete_notification
    end
  end
end

app/models/incase_import.rb
class IncaseImport < ApplicationRecord
  has_one_attached :file, dependent: :destroy
  has_many :incase_import_columns, dependent: :destroy
  accepts_nested_attributes_for :incase_import_columns, allow_destroy: true

  validate :file_size
  after_create_commit { broadcast_prepend_to 'incase_imports' }

  scope :active, -> { where(active: true) }

  def self.ransackable_attributes(auth_object = nil)
    IncaseImport.attribute_names
  end

  def self.ransackable_associations(auth_object = nil)
    ['incase_import_columns']
  end


  def self.import_attributes
    our_fields = {}
    not_use_incase_attr = %w[id created_at updated_at incase_status_id incase_tip_id]
    not_use_incase_item_attr = %w[id created_at updated_at incase_id incase_item_status_id variant_id vat]

    incase_attr = Incase.attribute_names.map { |ot| [I18n.t("helpers.label.incase.#{ot}"), "incase#" + ot] if !not_use_incase_attr.include?(ot) }
    incase_item_attr = IncaseItem.attribute_names.map { |ot| [I18n.t("helpers.label.incase_item.#{ot}"), "incase_item#" + ot] if !not_use_incase_item_attr.include?(ot) }
    our_fields[I18n.t('helpers.label.incase_import.incase')] = incase_attr.reject(&:blank?)
    our_fields[I18n.t('helpers.label.incase_import.incase_item')] = incase_item_attr.reject(&:blank?)
    our_fields
  end

  def file_size
    return unless file.attached?

    unless file.blob.byte_size <= 10.megabyte
      errors.add(:file, 'is too big')
    end

    acceptable_types = ['text/csv', 'text/xls', 'text/xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel']
    puts file.content_type
    unless acceptable_types.include?(file.content_type)
      errors.add(:file, 'must be a CSV or XLS')
    end
  end
  
end

app/controllers/incase_imports_controller.rb
class IncaseImportsController < ApplicationController
  load_and_authorize_resource
  before_action :set_incase_import, only: %i[show edit update import_start check_import destroy]
  before_action :validate_params, only: [:update]
  include SearchQueryRansack
  include DownloadExcel

  def index
    @search = IncaseImport.ransack(search_params)
    @search.sorts = "id desc" if @search.sorts.empty?
    @incase_imports = @search.result(distinct: true).paginate(page: params[:page], per_page: 100)
    respond_to do |format|
      format.html
    end
  end

  def show
  end

  def new
    @incase_import = IncaseImport.new
  end

  def edit
    if @incase_import.incase_import_columns.size < 1
      service = Incase::Import.new(@incase_import)
      header_data = service.header
      if header_data
        data = header_data.map { |d| {column_file: d, column_system: nil} }
        @incase_import.incase_import_columns.create!(data)
      else
        flash[:alert] = 'Import file not valid'
      end
    end
  end

  def create
    @incase_import = IncaseImport.new(incase_import_params)

    respond_to do |format|
      if @incase_import.save
        flash.now[:success] = t(".success")
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update(IncaseImport.new, ''),
            render_turbo_flash
          ]
        end
        format.html { redirect_to edit_incase_import_url(@incase_import), notice: 'File uploaded' }
        format.json { render :show, status: :created, location: @incase_import }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @incase_import.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    success, message = validate_params
    if success
      respond_to do |format|
        if @incase_import.update(incase_import_params)
          format.html { redirect_to incase_import_url(@incase_import), notice: 'Настройки импорта сохранены' }
          format.json { render :show, status: :ok, location: @incase_import }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @incase_import.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:notice] = message
      render :edit, status: :unprocessable_entity
    end
  end

  def check
    IncaseImportCheckFileJob.perform_later(@incase_import, current_user.id)
    respond_to do |format|
      format.turbo_stream
    end
  end

  def start # get
    IncaseImportStartImportJob.perform_later(@incase_import, current_user.id)
    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @incase_import.destroy

    respond_to do |format|
      format.html { redirect_to incase_imports_url, notice: 'Incase import was successfully destroyed.' }
      format.json { head :no_content }
      format.turbo_stream { flash.now[:success] = t('.success') }
    end
  end

  private

  def set_incase_import
    @incase_import = IncaseImport.find(params[:id])
  end

  def incase_import_params
    params.require(:incase_import).permit(:check, :active, :title, :report, :file, :uniq_field, :file, 
      incase_import_columns_attributes: [:id, :incase_import_id, :column_file, :column_system, :_destroy])
  end

  def validate_params
    status = []
    message = []
    uniq_field = params[:incase_import][:uniq_field]

    # puts "strategy: product // "
    # message.push('strategy: product //')
    system = params[:incase_import][:incase_import_columns_attributes].values.map { |c| c['column_system'] }.reject(&:blank?)
    puts "system => #{system.inspect}"
    status.push(system.include?(uniq_field) ? true : false)
    message.push(system.include?(uniq_field) ? '' : 'Need set uniq_field column')
    # status.push( system.include?('product#name') ? true : false )
    # message.push( system.include?('product#name') ? '' : 'Need product name' )
    # status.push( system.include?('product#price') ? true : false )
    # message.push( system.include?('product#price') ? '' : 'Need set price' )

    check_status = status.uniq.to_s == '[true]'
    [check_status, message.join(' ')]
  end
end

app/helpers/incase_imports_helper.rb
module IncaseImportsHelper
end

app/views/incase_imports/_check_import_info.html.erb
<div class="card-header">Проверили файл импорта</div>

<div class="card-body">
    <p>Информация из файла</p>
    <div class='border border-success text-success p-3'>
        <% message[:success].uniq.each do |item| %>
            <p><%= item %></p>
        <% end %>
    </div>
    <%= tag.div class: 'border border-danger text-danger mt-2 p-3' do %>
        <% message[:errors].uniq.each do |item| %>
            <p><%= item %></p>
        <% end %>
    <% end if message[:errors].size > 0 %>
</div>
<div class="card-footer">
    <div class="btn-group" role="group" aria-label="import button group">
        <%= form_for [incase_import], url: start_incase_imports_path(incase_import), html: { multipart: true }, method: :get, data: {turbo_stream: true} do |f| %>
            <%= f.submit 'Start', class: 'btn btn-primary', id: "import_start_button" %>
        <% end if success%>
        <%= link_to t('back'), incase_imports_path, class: "btn btn-outline-primary", data: { turbo_frame: :_top } %>
    </div>
</div>

app/views/incase_imports/_form.html.erb
<div class="card">
  <div class="card-header"><%= IncaseImport.model_name.human(count: 2)%></div>

  <%= form_with(model: incase_import, data: { turbo: false }) do |f| %>

  <div class="card-body">
    <div class="row mb-4">
      <%= render 'shared/errors', object: incase_import%>
      <div class="col-2 form-group checkbox">
        <div class="form-check form-switch">
          <%= f.check_box :active, {class: "form-check-input", role: "switch"} %>
          <%= f.label :active, class: "form-check-label"%>
        </div>
      </div>
      <div class="col-6 form-group checkbox">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= f.label :uniq_field, class: "form-label" %>
        <%= f.select :uniq_field,  [['Номер убытка','incase#unumber'],['Номер машины','incase#carnumber']], {}, { class: "form-select" }%>
      </div>
    </div>
    <div class="row">
      <div class="col-4 mb-2"><b>Колонки из файла</b></div>
      <div class="col-8 mb-2"><b>Системные поля</b></div>

      <%= f.fields_for :incase_import_columns do |ff| %>
        <div class="col-4 mb-1">
          <%= ff.hidden_field :column_file %>
          <%= label_tag "#{ff.object.column_file}", ff.object.column_file %>
        </div>
        <div class="col-8 mb-1">
          <%= ff.select :column_system, grouped_options_for_select( IncaseImport.import_attributes, 
                                                                    selected: ff.object.column_system.present? ? ff.object.column_system : selected_value_from_group(ff.object.column_file)), 
                                                                    {include_blank: true}, { class: "form-select" }%>
        </div>
      <%end%>
    </div>
  </div>
  <div class="card-footer">
      <%= f.submit t('save'),class: "btn btn-primary", data: {disable_with: false} %>
      <%= link_to t('back'), incase_imports_path, class: "btn btn-outline-primary" %>
  </div>


  <% end %>

</div>

app/views/incase_imports/_import_finish.html.erb
    <div class='border border-success text-success p-3'>
        <% message[:success].uniq.each do |item| %>
            <p><%= item %></p>
        <% end %>
    </div>
    <%= tag.div class: 'border border-danger text-danger mt-2 p-3' do %>
        <% message[:errors].uniq.each do |item| %>
            <p><%= item %></p>
        <% end %>
    <% end if message[:errors].size > 0 %>

app/views/incase_imports/_incase_import.html.erb
<%= turbo_frame_tag incase_import, class: "d-flex list-group-item py-2 border-start-0 border-end-0 align-items-center row" do %>
    <%= tag.div class: "col-1" do %>
        <%=tag.div class: 'form-check' do %>
            <%= check_box_tag "incase_import_ids[]", incase_import.id, false, {class: 'checkboxes form-check-input', data: { 'selectall_target': 'checkbox', action: "change->selectall#toggleParent"}, form: :print_etiketki_form } %>
            <%=tag.label class: 'form-check-label' do %><%= tag.b( incase_import.id ) %><% end %>
        <% end %>
    <% end %>
    
    <%= tag.div(class: "col-2 d-flex justify-content-between align-items-center") do %>
        <% if incase_import.active %>
            <button class="btn btn-outline-info" disabled="disabled" type="button">active<i class="bi bi-check-circle ms-1"></i></button>
        <% end %>
    <% end %>

    <%= tag.div(incase_import.title, class: "col-3")%>
    <%= tag.div(incase_import.report, class: "col-1")%>
    <%= tag.div("", class: "col-1") do %>
        <%= link_to 'file', rails_blob_path(incase_import.file, disposition: 'attachment') %>
    <% end %>
    <%= tag.div("", class: "col-2 #{incase_import.uniq_field}") do %>
        <%= incase_import.uniq_field.present? ? t("helpers.label.incase.#{incase_import.uniq_field.split('#').last}") : '' %>
    <% end %>
    <div class= "col-2 d-flex justify-content-end gap-2 align-items-center" id="buttons-<%=incase_import.id%>">
      <%= link_to eye_icon, incase_import, class: "", data: { turbo_frame: :_top } %>
      <%= render 'shared/edit_delete_link', object: incase_import %>
    </div>
<% end %>

app/views/incase_imports/check.turbo_stream.erb
<%= turbo_stream.update @incase_import do %>
    <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
        <span role="status">Running...</span>
    </button>
<% end %>

app/views/incase_imports/destroy.turbo_stream.erb
<%= turbo_stream.remove @incase_import %>
<%= prepend_flash %>

app/views/incase_imports/edit.html.erb
<%= render "form", incase_import: @incase_import %>

app/views/incase_imports/index.html.erb
<div class="row index-head mb-3">
  <div class="col-md-6 index-head__title">
    <h1 class="h3 d-inline align-middle"><%= IncaseImport.model_name.human(count: 2)%></h1>
  </div>
  <div class="col-md-6 d-flex justify-content-end index-head__buttons">
    <%= form_with url: bulk_print_incase_imports_path, method: :post, id: :bulk_action_form  do |f| %>
      <% if Templ.incase_import_print.presence %>
        <%= button_print %>
        <ul class="dropdown-menu">
          <% Templ.incase_import_print.each do |templ|%>
            <%= f.button type: :submit, value: "templ_id##{templ.id}", class: "dropdown-item" do %>
              <%= templ.title %>
            <% end %>
          <% end %>
        </ul>
      <% end %>
      <%= render 'shared/download_excel_buttons', f: f, object: IncaseImport.new %>
    <% end %>

    <%= render 'shared/index_filter' if lookup_context.find_all("incase_imports/_filter").any? %>
    <%= link_to arrow_clockwise_icon, incase_imports_path(search_cancel: true), class: 'btn btn-outline-primary me-2', data: {turbo: false}  %>
    <%= link_to add_icon, new_incase_import_path, class: "btn btn-primary", data: {turbo_frame: dom_id(IncaseImport.new) } %>
  </div>
</div>

<%= render 'filter', q: @search, title: 'Incase Import filter' if lookup_context.find_all("incase_imports/_filter").any?%>

<div class="card">
  <div class="card-header pb-0">
    <div class="card-actions float-end">
      <div class="dropdown position-relative">
        <a href="#" data-bs-toggle="dropdown" data-bs-display="static">
          <%= more_icon%>
        </a>
        <div class="dropdown-menu dropdown-menu-end">
          <%= link_to '.xlsx', incase_imports_path(request.parameters.merge(format: 'zip')), class:"dropdown-item", data: {turbo_prefetch: false} %>
        </div>
      </div>
    </div>
    <h5 class="card-title mb-0"></h5>
    <h5 class="card-title mb-0">Всего: <%= IncaseImport.all.count %></br><%= "Выбрано: "+@incase_imports.total_entries.to_s if @incase_imports.size > 0 &&  @incase_imports.size != IncaseImport.all.count %></h5>
  </div>
  <div class="card-body">
      <div class="col-sm-12 list-group list-group-striped" data-controller="selectall">
        <div class="row">
          <%= turbo_frame_tag IncaseImport.new %>  
        </div>
        
        <div class="row py-2 px-4">
          <%= div_check_box_tag_all %>
          <%= tag.div( t( 'helpers.label.incase_import.active'), class: 'col-2 fw-semibold' ) %>
          <%= tag.div( t( 'helpers.label.incase_import.title'), class: 'col-3 fw-semibold' ) %> 
          <%= tag.div( t( 'helpers.label.incase_import.report'), class: 'col-1 fw-semibold' ) %>
          <%= tag.div( t( 'helpers.label.incase_import.file'), class: 'col-1 fw-semibold' ) %>
          <%= tag.div( t( 'helpers.label.incase_import.uniq_field'), class: 'col-2 fw-semibold' ) %>
          <%= tag.div('', class: 'col-2 fw-semibold')%>
        </div>

        <%= turbo_stream_from "incase_imports" %>
        <%= turbo_frame_tag 'incase_imports' do %>
            <%= render @incase_imports %>
        <% end %>

      </div>
      
      <%= render "shared/paginate", f: @incase_imports %>

  </div>
</div>

app/views/incase_imports/new.html.erb
<%= turbo_frame_tag dom_id(@incase_import) do %>
<div class="card">
  <div class="card-header"><b>Attention</b> only use  (Excel 2000/97 .xlsx) or csv (column separate "comma",  "utf-8")</div>
  <% form_class =  @incase_import.new_record? ? "new_import" : ''%>
  <%= form_with(model: @incase_import, data: {controller: "file-upload", upload_target: "form", turbo: false}, class: form_class) do |f| %>
    <%= render 'shared/errors', object: @incase_import%>
    <div class="card-body">
      <div class="row">
        <div class="col-5 form-group checkbox visually-hidden">
          <%= label_tag :active do %>
            <%= f.check_box :active %>
            <%= t('helpers.label.incase_import.active') %>
          <% end %>
        </div>
        <%= f.text_field :title, value: "test import"+ Time.now.to_s, class: "form-control visually-hidden" %>
        <div class="col-6 mt-2 mb-2">
            <%= f.file_field :file, multiple: false, 
                                          direct_upload: true, data: { file_upload_target: "input", action: "change->file-upload#go" },
                                          accept: '.csv,.xls,.xlsx', class: 'file' %>
        </div>
      
        <div class="col-6 mt-2 mb-2">
          <%= f.submit t('save'), class: "btn btn-primary visually-hidden", data: { disable_with: false, file_upload_target: "endbutton" } %>
          <%= link_to close_icon, incase_imports_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="progress bg-transparent" data-file-upload-target="progress" 
                                                role="progressbar" 
                                                aria-label="file upload progressbar" 
                                                aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/incase_imports/show.html.erb
<div class="card">
<%= turbo_stream_from current_user, "check_incase_imports" if user_signed_in? %>
<%= turbo_frame_tag @incase_import do %>
  <div class="card-header"><%= t('import_info')%></div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <span class="h5">Title</span>
                <span><%= @incase_import.title %></span>
            </div>
            <div class="col-12">
                <span class="h5">File</span>
                <span><%= link_to 'file', rails_blob_path(@incase_import.file, disposition: 'attachment') %></span>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="btn-group" role="group" aria-label="import button group">
            <%= link_to t('edit'), edit_incase_import_path(@incase_import), class: "btn btn-light", data: { turbo_frame: :_top } if can? :edit, @incase_import %>
            <%# form_for [@incase_import], url: check_incase_imports_path, html: { multipart: true }, method: :get do |f| %>
                <%# f.submit 'Check', class: 'btn btn-primary', id: "import_start_button" %>
            <%# end %>
            <%= link_to t('check'), check_incase_imports_path, class: "btn btn-primary", data: {turbo_stream: true} %>
            <%= link_to t('cancel'), incase_imports_path, class: "btn btn-outline-primary", data: { turbo_frame: :_top } %>
        </div>
    </div>
<% end %>
</div>

app/views/incase_imports/start.turbo_stream.erb
<%= turbo_stream.update @incase_import do %>
    <div class="card-body">
    </div>
    <div class="card-footer">
        <div class="d-flex row">
            <div class="col-12">
                <%= link_to t('back'), incase_imports_path, class: "btn btn-outline-primary", data: { turbo_frame: :_top } %>
            </div>
        </div>
    </div>
<% end %>

<%= turbo_stream.update "modal", "" %>

<%= turbo_stream.update "modal" do %>
    <div class="d-flex row">
        <div class="col-12">Информация об импорте появится в Оповещениях после окончания процесса</div>
        <div class="col-12">или</div>
        <div class="col-12">дождаться информации об окончании в этом окне</div>
        <div class="col-12"><%= link_to "Перейти в раздел", '/notifications', class: "btn btn-link px-0" , data: { turbo_frame: :_top } %></div>
        <div class="col-12">
            <button class="btn btn-primary" type="button" disabled>
                <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                <span role="status">Running...</span>
            </button>
        </div>
    </div>
<% end %>

<%= turbo_stream_action_tag :open_modal, targets: '.modal' %>